language: node_js
sudo: false
node_js:
- 5.12.0
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
- npm run ci
- . ./deploy_prep.sh
deploy:
  provider: s3
  region: us-west-2
  bucket: raging-goblin-ui
  local-dir: public
  acl: public_read
  skip_cleanup: true
  on:
    all_branches: true
    condition: $ENV_TAG
